spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER_CLASS}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
