spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reg2024
    username: reg2024
    password: Chsp@ssw0rd
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop