spring:
  api_key: ${API_KEY}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER_CLASS}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
  mail:
    host: smtp.gmail.com
    username: reg.a@chs.ac.th
    password: itevsfjcefigrdvo
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

file:
  upload-dir: ${FILE_UPLOAD_DIR}