name: Deploy REG2024 BE

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/adminreg/reg-be
            git reset --hard origin/develop
            git fetch --all
            git pull origin develop
            chmod +x deploy.sh
            ./deploy.sh

